### ISSUE TITLE
Invalid parameter value detected; execution cannot continue. : Username is not valid.

### ISSUE THREAD

**Issue by linsharon** [catalyst/moodle-assignsubmission_maharaws#40]
I encountered the following error when using the plugin and eventually resolved it. Steps of resolving this error are documented and shared in the attached file. 

<EXCEPTION class="WebserviceInvalidParameterException"> <ERRORCODE>invalidparameter</ERRORCODE> <MESSAGE> Invalid parameter value detected; execution cannot continue. : Username is not valid. </MESSAGE> </EXCEPTION>

[Bug fixing #1 admin unable to view mahara assignment submissions.pdf](https://github.com/catalyst/moodle-assignsubmission_maharaws/files/7958358/Bug.fixing.1.admin.unable.to.view.mahara.assignment.submissions.pdf)

**Comment by danmarsden** [comment]
Thanks for providing that extra information - hopefully it may be useful for others who encounter this issue - as it seems to be a configuration issue and you have resolved it as described in your document, I'm flagging this as closed but please let us know if we have missed anything or you believe this is an issue within the moodle plugin rather than Mahara codebase - thanks!
